export const actions = {
	ADDING_MODE: 'ADDING_MODE',
	ADD_NEW_TASK_FULLFIELD: 'ADD_NEW_TASK_FULLFIELD',
	GET_DATA_PENDING: 'GET_DATA_PENDING',
	GET_DATA_FULFIELD: 'GET_DATA_FULFIELD',
	GET_DATA_REJECTED: 'GET_DATA_REJECTED',
	UPDATE_TASK_FULFIELD: 'UPDATE_TASK',
	DELETE_TASK_FULFIELD: 'DELETE_TASK',
	OPEN_SEARCH_MODE: 'OPEN_SEARCH_MODE',
	SET_SEARCH_PHRASE: 'SET_SEARCH_PHRASE',
	ACTION_SORTED: 'ACTION_SORTED',
};
