export const actions = {
	ADDING_MODE: 'ADDING_MODE',
	ADD_NEW_TASK: 'ADD_NEW_TASK',
	GET_DATA_TODOS: 'GET_DATA_TODOS',
	UPDATE_TASK: 'UPDATE_TASK',

	ERROR_REQUEST: 'ERROR_REQUEST',

	ACTION_SORTED: 'ACTION_SORTED',
};
