export const actions = {
	ADDING_MODE: 'ADDING_MODE',
	ADD_NEW_TASK: 'ADD_NEW_TASK',
	GET_DATA_TODOS: 'GET_DATA_TODOS',
	UPDATE_TASK: 'UPDATE_TASK',
	DELETE_TASK: 'DELETE_TASK',
	ERROR_REQUEST: 'ERROR_REQUEST',
	OPEN_SEARCH_MODE: 'OPEN_SEARCH_MODE',
	SET_SEARCH_PHRASE: 'SET_SEARCH_PHRASE',
	ACTION_SORTED: 'ACTION_SORTED',
};
